# Generated by Django 3.0.6 on 2020-05-09 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_variation'),
    ]

    operations = [
        migrations.CreateModel(
            name='stock',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.products')),
                ('date', models.DateField(auto_now=True)),
                ('quantity', models.IntegerField()),
                ('sale_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
            ],
        ),
    ]
